on: [push, workflow_dispatch]

name: Test creation of Pull Request

jobs:
  test:
    name: Test if PR is created
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: checkout Planit-DevOps
        uses: actions/checkout@v3
        with:
          repository: Planit-Study/Planit-DevOps
          path: ./Planit-DevOps
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR
        env:
          GHB_PAT: ${{ secrets.GITHUB_PAT }}
          DEVOPS_REPO_URL: ${{ secrets.DEVOPS_REPO_URL }}
          COMMIT_HASH: ${{ github.sha }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./some.sh
          ./some.sh
